### ISSUE TITLE
Porque razón estas definiciones son publicas y no privadas

### ISSUE THREAD

**Issue by evolentini** [snorkman88/TSE-TP3-#2]
En principio no hay necesidad de hacer estas definiciones publicas, solo le interesan al archivo `leds.c`, y en ese caso deberían estar definidas en el mismo archivo `.c` en lugar de en el archivo `.h`

https://github.com/snorkman88/TSE-TP3-/blob/ecdc60d534f142f6bd5913e17ac65abc8471dc5c/leds/src/leds.h#L3-L4

**Comment by snorkman88** [comment]
corregido
