### ISSUE TITLE
No se sube código binario al repositorio

### ISSUE THREAD

**Issue by evolentini** [snorkman88/TSE-TP3-#3]
La carpeta `build` se debería agregar en el archivo `.gitignore` y eliminar el contenido del control de versiones

**Comment by snorkman88** [comment]
Entendido.
Creo que ya estaría corregido.
Gracias Esteban.

**Comment by evolentini** [comment]
Si, esto resta resulto. Te faltan las constantes mágicas del otro issue y estaría listo.
